# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cds2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncds2.proto\x12\x0forg.signal.cds2\"M\n\x14\x43lientHandshakeStart\x12\x0e\n\x06pubkey\x18\x01 \x01(\x0c\x12\x10\n\x08\x65vidence\x18\x02 \x01(\x0c\x12\x13\n\x0b\x65ndorsement\x18\x03 \x01(\x0c\x62\x06proto3')



_CLIENTHANDSHAKESTART = DESCRIPTOR.message_types_by_name['ClientHandshakeStart']
ClientHandshakeStart = _reflection.GeneratedProtocolMessageType('ClientHandshakeStart', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTHANDSHAKESTART,
  '__module__' : 'cds2_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.cds2.ClientHandshakeStart)
  })
_sym_db.RegisterMessage(ClientHandshakeStart)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTHANDSHAKESTART._serialized_start=31
  _CLIENTHANDSHAKESTART._serialized_end=108
# @@protoc_insertion_point(module_scope)
