# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Emoji.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0b\x45moji.proto\x12\x06signal"5\n\rJumbomojiPack\x12$\n\x05items\x18\x01 \x03(\x0b\x32\x15.signal.JumbomojiItem",\n\rJumbomojiItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x42+\n\'org.thoughtcrime.securesms.emoji.protosP\x01\x62\x06proto3'
)


_JUMBOMOJIPACK = DESCRIPTOR.message_types_by_name["JumbomojiPack"]
_JUMBOMOJIITEM = DESCRIPTOR.message_types_by_name["JumbomojiItem"]
JumbomojiPack = _reflection.GeneratedProtocolMessageType(
    "JumbomojiPack",
    (_message.Message,),
    {
        "DESCRIPTOR": _JUMBOMOJIPACK,
        "__module__": "Emoji_pb2",
        # @@protoc_insertion_point(class_scope:signal.JumbomojiPack)
    },
)
_sym_db.RegisterMessage(JumbomojiPack)

JumbomojiItem = _reflection.GeneratedProtocolMessageType(
    "JumbomojiItem",
    (_message.Message,),
    {
        "DESCRIPTOR": _JUMBOMOJIITEM,
        "__module__": "Emoji_pb2",
        # @@protoc_insertion_point(class_scope:signal.JumbomojiItem)
    },
)
_sym_db.RegisterMessage(JumbomojiItem)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n'org.thoughtcrime.securesms.emoji.protosP\001"
    _JUMBOMOJIPACK._serialized_start = 23
    _JUMBOMOJIPACK._serialized_end = 76
    _JUMBOMOJIITEM._serialized_start = 78
    _JUMBOMOJIITEM._serialized_end = 122
# @@protoc_insertion_point(module_scope)
