# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExternalBackups.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x45xternalBackups.proto\x12\x06signal\"\x1e\n\x0cSvrAuthToken\x12\x0e\n\x06tokens\x18\x01 \x03(\tB-\n+org.thoughtcrime.securesms.absbackup.protosb\x06proto3')



_SVRAUTHTOKEN = DESCRIPTOR.message_types_by_name['SvrAuthToken']
SvrAuthToken = _reflection.GeneratedProtocolMessageType('SvrAuthToken', (_message.Message,), {
  'DESCRIPTOR' : _SVRAUTHTOKEN,
  '__module__' : 'ExternalBackups_pb2'
  # @@protoc_insertion_point(class_scope:signal.SvrAuthToken)
  })
_sym_db.RegisterMessage(SvrAuthToken)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+org.thoughtcrime.securesms.absbackup.protos'
  _SVRAUTHTOKEN._serialized_start=33
  _SVRAUTHTOKEN._serialized_end=63
# @@protoc_insertion_point(module_scope)
