# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fingerprint.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x66ingerprint.proto\x12\x18signal.proto.fingerprint"%\n\x12LogicalFingerprint\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c"\xba\x01\n\x14\x43ombinedFingerprints\x12\x0f\n\x07version\x18\x01 \x01(\r\x12G\n\x11local_fingerprint\x18\x02 \x01(\x0b\x32,.signal.proto.fingerprint.LogicalFingerprint\x12H\n\x12remote_fingerprint\x18\x03 \x01(\x0b\x32,.signal.proto.fingerprint.LogicalFingerprint'
)


_LOGICALFINGERPRINT = DESCRIPTOR.message_types_by_name["LogicalFingerprint"]
_COMBINEDFINGERPRINTS = DESCRIPTOR.message_types_by_name["CombinedFingerprints"]
LogicalFingerprint = _reflection.GeneratedProtocolMessageType(
    "LogicalFingerprint",
    (_message.Message,),
    {
        "DESCRIPTOR": _LOGICALFINGERPRINT,
        "__module__": "fingerprint_pb2",
        # @@protoc_insertion_point(class_scope:signal.proto.fingerprint.LogicalFingerprint)
    },
)
_sym_db.RegisterMessage(LogicalFingerprint)

CombinedFingerprints = _reflection.GeneratedProtocolMessageType(
    "CombinedFingerprints",
    (_message.Message,),
    {
        "DESCRIPTOR": _COMBINEDFINGERPRINTS,
        "__module__": "fingerprint_pb2",
        # @@protoc_insertion_point(class_scope:signal.proto.fingerprint.CombinedFingerprints)
    },
)
_sym_db.RegisterMessage(CombinedFingerprints)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _LOGICALFINGERPRINT._serialized_start = 47
    _LOGICALFINGERPRINT._serialized_end = 84
    _COMBINEDFINGERPRINTS._serialized_start = 87
    _COMBINEDFINGERPRINTS._serialized_end = 273
# @@protoc_insertion_point(module_scope)
