# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InternalSerialization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import SignalService_pb2 as SignalService__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1bInternalSerialization.proto\x12\ntextsecure\x1a\x13SignalService.proto"\xe4\x01\n\x19SignalServiceContentProto\x12.\n\x0clocalAddress\x18\x01 \x01(\x0b\x32\x18.textsecure.AddressProto\x12+\n\x08metadata\x18\x02 \x01(\x0b\x32\x19.textsecure.MetadataProto\x12\x37\n\x11legacyDataMessage\x18\x03 \x01(\x0b\x32\x1a.signalservice.DataMessageH\x00\x12)\n\x07\x63ontent\x18\x04 \x01(\x0b\x32\x16.signalservice.ContentH\x00\x42\x06\n\x04\x64\x61ta"\xb7\x02\n\x1aSignalServiceEnvelopeProto\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x17\n\x0fsourceServiceId\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65viceId\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\x0c\x12\x11\n\ttimestamp\x18\x07 \x01(\x03\x12\x1f\n\x17serverReceivedTimestamp\x18\x08 \x01(\x03\x12 \n\x18serverDeliveredTimestamp\x18\t \x01(\x03\x12\x12\n\nserverGuid\x18\n \x01(\t\x12\x1c\n\x14\x64\x65stinationServiceId\x18\x0b \x01(\t\x12\x14\n\x06urgent\x18\x0c \x01(\x08:\x04true\x12\r\n\x05story\x18\r \x01(\x08\x12\x16\n\x0ereportingToken\x18\x0e \x01(\x0cJ\x04\x08\x03\x10\x04J\x04\x08\x05\x10\x06"\xfa\x01\n\rMetadataProto\x12)\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32\x18.textsecure.AddressProto\x12\x14\n\x0csenderDevice\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x1f\n\x17serverReceivedTimestamp\x18\x05 \x01(\x03\x12 \n\x18serverDeliveredTimestamp\x18\x06 \x01(\x03\x12\x14\n\x0cneedsReceipt\x18\x04 \x01(\x08\x12\x12\n\nserverGuid\x18\x07 \x01(\t\x12\x0f\n\x07groupId\x18\x08 \x01(\x0c\x12\x17\n\x0f\x64\x65stinationUuid\x18\t \x01(\t"*\n\x0c\x41\x64\x64ressProto\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\x0c\n\x04\x65\x31\x36\x34\x18\x02 \x01(\tB>\n:org.whispersystems.signalservice.internal.serialize.protosP\x01'
)


_SIGNALSERVICECONTENTPROTO = DESCRIPTOR.message_types_by_name[
    "SignalServiceContentProto"
]
_SIGNALSERVICEENVELOPEPROTO = DESCRIPTOR.message_types_by_name[
    "SignalServiceEnvelopeProto"
]
_METADATAPROTO = DESCRIPTOR.message_types_by_name["MetadataProto"]
_ADDRESSPROTO = DESCRIPTOR.message_types_by_name["AddressProto"]
SignalServiceContentProto = _reflection.GeneratedProtocolMessageType(
    "SignalServiceContentProto",
    (_message.Message,),
    {
        "DESCRIPTOR": _SIGNALSERVICECONTENTPROTO,
        "__module__": "InternalSerialization_pb2",
        # @@protoc_insertion_point(class_scope:textsecure.SignalServiceContentProto)
    },
)
_sym_db.RegisterMessage(SignalServiceContentProto)

SignalServiceEnvelopeProto = _reflection.GeneratedProtocolMessageType(
    "SignalServiceEnvelopeProto",
    (_message.Message,),
    {
        "DESCRIPTOR": _SIGNALSERVICEENVELOPEPROTO,
        "__module__": "InternalSerialization_pb2",
        # @@protoc_insertion_point(class_scope:textsecure.SignalServiceEnvelopeProto)
    },
)
_sym_db.RegisterMessage(SignalServiceEnvelopeProto)

MetadataProto = _reflection.GeneratedProtocolMessageType(
    "MetadataProto",
    (_message.Message,),
    {
        "DESCRIPTOR": _METADATAPROTO,
        "__module__": "InternalSerialization_pb2",
        # @@protoc_insertion_point(class_scope:textsecure.MetadataProto)
    },
)
_sym_db.RegisterMessage(MetadataProto)

AddressProto = _reflection.GeneratedProtocolMessageType(
    "AddressProto",
    (_message.Message,),
    {
        "DESCRIPTOR": _ADDRESSPROTO,
        "__module__": "InternalSerialization_pb2",
        # @@protoc_insertion_point(class_scope:textsecure.AddressProto)
    },
)
_sym_db.RegisterMessage(AddressProto)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n:org.whispersystems.signalservice.internal.serialize.protosP\001"
    )
    _SIGNALSERVICECONTENTPROTO._serialized_start = 65
    _SIGNALSERVICECONTENTPROTO._serialized_end = 293
    _SIGNALSERVICEENVELOPEPROTO._serialized_start = 296
    _SIGNALSERVICEENVELOPEPROTO._serialized_end = 607
    _METADATAPROTO._serialized_start = 610
    _METADATAPROTO._serialized_end = 860
    _ADDRESSPROTO._serialized_start = 862
    _ADDRESSPROTO._serialized_end = 904
# @@protoc_insertion_point(module_scope)
