# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JobData.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ResumableUploads_pb2 as ResumableUploads__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rJobData.proto\x12\x06signal\x1a\x16ResumableUploads.proto\"e\n\x16\x43\x61llSyncEventJobRecord\x12\x13\n\x0brecipientId\x18\x01 \x01(\x04\x12\x0e\n\x06\x63\x61llId\x18\x03 \x01(\x04\x12\x11\n\tdirection\x18\x04 \x01(\r\x12\r\n\x05\x65vent\x18\x05 \x01(\rJ\x04\x08\x02\x10\x03\"G\n\x14\x43\x61llSyncEventJobData\x12/\n\x07records\x18\x01 \x03(\x0b\x32\x1e.signal.CallSyncEventJobRecord\"9\n$CallLinkRefreshSinceTimestampJobData\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\"/\n\x17\x43\x61llLogEventSendJobData\x12\x14\n\x0c\x63\x61llLogEvent\x18\x01 \x01(\x0c\"\x97\x01\n\x19\x43\x61llLinkUpdateSendJobData\x12\x16\n\x0e\x63\x61llLinkRoomId\x18\x01 \x01(\t\x12\x39\n\x04type\x18\x02 \x01(\x0e\x32&.signal.CallLinkUpdateSendJobData.TypeH\x00\x88\x01\x01\"\x1e\n\x04Type\x12\n\n\x06UPDATE\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x42\x07\n\x05_type\"o\n\x17\x41ttachmentUploadJobData\x12\x14\n\x0c\x61ttachmentId\x18\x01 \x01(\x04\x12)\n\nuploadSpec\x18\x03 \x01(\x0b\x32\x10.ResumableUploadH\x00\x88\x01\x01\x42\r\n\x0b_uploadSpecJ\x04\x08\x02\x10\x03\"3\n\x12PreKeysSyncJobData\x12\x1d\n\x15\x66orceRefreshRequested\x18\x01 \x01(\x08\"0\n\x18\x41rchiveAttachmentJobData\x12\x14\n\x0c\x61ttachmentId\x18\x01 \x01(\x04\"t\n ArchiveAttachmentBackfillJobData\x12\x19\n\x0c\x61ttachmentId\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12$\n\nuploadSpec\x18\x02 \x01(\x0b\x32\x10.ResumableUploadB\x0f\n\r_attachmentIdB*\n&org.thoughtcrime.securesms.jobs.protosP\x01\x62\x06proto3')



_CALLSYNCEVENTJOBRECORD = DESCRIPTOR.message_types_by_name['CallSyncEventJobRecord']
_CALLSYNCEVENTJOBDATA = DESCRIPTOR.message_types_by_name['CallSyncEventJobData']
_CALLLINKREFRESHSINCETIMESTAMPJOBDATA = DESCRIPTOR.message_types_by_name['CallLinkRefreshSinceTimestampJobData']
_CALLLOGEVENTSENDJOBDATA = DESCRIPTOR.message_types_by_name['CallLogEventSendJobData']
_CALLLINKUPDATESENDJOBDATA = DESCRIPTOR.message_types_by_name['CallLinkUpdateSendJobData']
_ATTACHMENTUPLOADJOBDATA = DESCRIPTOR.message_types_by_name['AttachmentUploadJobData']
_PREKEYSSYNCJOBDATA = DESCRIPTOR.message_types_by_name['PreKeysSyncJobData']
_ARCHIVEATTACHMENTJOBDATA = DESCRIPTOR.message_types_by_name['ArchiveAttachmentJobData']
_ARCHIVEATTACHMENTBACKFILLJOBDATA = DESCRIPTOR.message_types_by_name['ArchiveAttachmentBackfillJobData']
_CALLLINKUPDATESENDJOBDATA_TYPE = _CALLLINKUPDATESENDJOBDATA.enum_types_by_name['Type']
CallSyncEventJobRecord = _reflection.GeneratedProtocolMessageType('CallSyncEventJobRecord', (_message.Message,), {
  'DESCRIPTOR' : _CALLSYNCEVENTJOBRECORD,
  '__module__' : 'JobData_pb2'
  # @@protoc_insertion_point(class_scope:signal.CallSyncEventJobRecord)
  })
_sym_db.RegisterMessage(CallSyncEventJobRecord)

CallSyncEventJobData = _reflection.GeneratedProtocolMessageType('CallSyncEventJobData', (_message.Message,), {
  'DESCRIPTOR' : _CALLSYNCEVENTJOBDATA,
  '__module__' : 'JobData_pb2'
  # @@protoc_insertion_point(class_scope:signal.CallSyncEventJobData)
  })
_sym_db.RegisterMessage(CallSyncEventJobData)

CallLinkRefreshSinceTimestampJobData = _reflection.GeneratedProtocolMessageType('CallLinkRefreshSinceTimestampJobData', (_message.Message,), {
  'DESCRIPTOR' : _CALLLINKREFRESHSINCETIMESTAMPJOBDATA,
  '__module__' : 'JobData_pb2'
  # @@protoc_insertion_point(class_scope:signal.CallLinkRefreshSinceTimestampJobData)
  })
_sym_db.RegisterMessage(CallLinkRefreshSinceTimestampJobData)

CallLogEventSendJobData = _reflection.GeneratedProtocolMessageType('CallLogEventSendJobData', (_message.Message,), {
  'DESCRIPTOR' : _CALLLOGEVENTSENDJOBDATA,
  '__module__' : 'JobData_pb2'
  # @@protoc_insertion_point(class_scope:signal.CallLogEventSendJobData)
  })
_sym_db.RegisterMessage(CallLogEventSendJobData)

CallLinkUpdateSendJobData = _reflection.GeneratedProtocolMessageType('CallLinkUpdateSendJobData', (_message.Message,), {
  'DESCRIPTOR' : _CALLLINKUPDATESENDJOBDATA,
  '__module__' : 'JobData_pb2'
  # @@protoc_insertion_point(class_scope:signal.CallLinkUpdateSendJobData)
  })
_sym_db.RegisterMessage(CallLinkUpdateSendJobData)

AttachmentUploadJobData = _reflection.GeneratedProtocolMessageType('AttachmentUploadJobData', (_message.Message,), {
  'DESCRIPTOR' : _ATTACHMENTUPLOADJOBDATA,
  '__module__' : 'JobData_pb2'
  # @@protoc_insertion_point(class_scope:signal.AttachmentUploadJobData)
  })
_sym_db.RegisterMessage(AttachmentUploadJobData)

PreKeysSyncJobData = _reflection.GeneratedProtocolMessageType('PreKeysSyncJobData', (_message.Message,), {
  'DESCRIPTOR' : _PREKEYSSYNCJOBDATA,
  '__module__' : 'JobData_pb2'
  # @@protoc_insertion_point(class_scope:signal.PreKeysSyncJobData)
  })
_sym_db.RegisterMessage(PreKeysSyncJobData)

ArchiveAttachmentJobData = _reflection.GeneratedProtocolMessageType('ArchiveAttachmentJobData', (_message.Message,), {
  'DESCRIPTOR' : _ARCHIVEATTACHMENTJOBDATA,
  '__module__' : 'JobData_pb2'
  # @@protoc_insertion_point(class_scope:signal.ArchiveAttachmentJobData)
  })
_sym_db.RegisterMessage(ArchiveAttachmentJobData)

ArchiveAttachmentBackfillJobData = _reflection.GeneratedProtocolMessageType('ArchiveAttachmentBackfillJobData', (_message.Message,), {
  'DESCRIPTOR' : _ARCHIVEATTACHMENTBACKFILLJOBDATA,
  '__module__' : 'JobData_pb2'
  # @@protoc_insertion_point(class_scope:signal.ArchiveAttachmentBackfillJobData)
  })
_sym_db.RegisterMessage(ArchiveAttachmentBackfillJobData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n&org.thoughtcrime.securesms.jobs.protosP\001'
  _CALLSYNCEVENTJOBRECORD._serialized_start=49
  _CALLSYNCEVENTJOBRECORD._serialized_end=150
  _CALLSYNCEVENTJOBDATA._serialized_start=152
  _CALLSYNCEVENTJOBDATA._serialized_end=223
  _CALLLINKREFRESHSINCETIMESTAMPJOBDATA._serialized_start=225
  _CALLLINKREFRESHSINCETIMESTAMPJOBDATA._serialized_end=282
  _CALLLOGEVENTSENDJOBDATA._serialized_start=284
  _CALLLOGEVENTSENDJOBDATA._serialized_end=331
  _CALLLINKUPDATESENDJOBDATA._serialized_start=334
  _CALLLINKUPDATESENDJOBDATA._serialized_end=485
  _CALLLINKUPDATESENDJOBDATA_TYPE._serialized_start=446
  _CALLLINKUPDATESENDJOBDATA_TYPE._serialized_end=476
  _ATTACHMENTUPLOADJOBDATA._serialized_start=487
  _ATTACHMENTUPLOADJOBDATA._serialized_end=598
  _PREKEYSSYNCJOBDATA._serialized_start=600
  _PREKEYSSYNCJOBDATA._serialized_end=651
  _ARCHIVEATTACHMENTJOBDATA._serialized_start=653
  _ARCHIVEATTACHMENTJOBDATA._serialized_end=701
  _ARCHIVEATTACHMENTBACKFILLJOBDATA._serialized_start=703
  _ARCHIVEATTACHMENTBACKFILLJOBDATA._serialized_end=819
# @@protoc_insertion_point(module_scope)
