# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeyValue.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0eKeyValue.proto\x12\x06signal"D\n\x17LeastActiveLinkedDevice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x13lastActiveTimestamp\x18\x02 \x01(\x04\x42,\n*org.thoughtcrime.securesms.keyvalue.protosb\x06proto3'
)


_LEASTACTIVELINKEDDEVICE = DESCRIPTOR.message_types_by_name["LeastActiveLinkedDevice"]
LeastActiveLinkedDevice = _reflection.GeneratedProtocolMessageType(
    "LeastActiveLinkedDevice",
    (_message.Message,),
    {
        "DESCRIPTOR": _LEASTACTIVELINKEDDEVICE,
        "__module__": "KeyValue_pb2",
        # @@protoc_insertion_point(class_scope:signal.LeastActiveLinkedDevice)
    },
)
_sym_db.RegisterMessage(LeastActiveLinkedDevice)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n*org.thoughtcrime.securesms.keyvalue.protos"
    _LEASTACTIVELINKEDDEVICE._serialized_start = 26
    _LEASTACTIVELINKEDDEVICE._serialized_end = 94
# @@protoc_insertion_point(module_scope)
