# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageProcessing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17MessageProcessing.proto\x12\rsignalservice"\x9c\x01\n\x10\x45nvelopeMetadata\x12\x17\n\x0fsourceServiceId\x18\x01 \x02(\x0c\x12\x12\n\nsourceE164\x18\x02 \x01(\t\x12\x16\n\x0esourceDeviceId\x18\x03 \x02(\x05\x12\x14\n\x0csealedSender\x18\x04 \x02(\x08\x12\x0f\n\x07groupId\x18\x05 \x01(\x0c\x12\x1c\n\x14\x64\x65stinationServiceId\x18\x06 \x02(\x0c"\x89\x01\n\x0f\x43ompleteMessage\x12\x10\n\x08\x65nvelope\x18\x01 \x02(\x0c\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\x0c\x12\x31\n\x08metadata\x18\x03 \x02(\x0b\x32\x1f.signalservice.EnvelopeMetadata\x12 \n\x18serverDeliveredTimestamp\x18\x04 \x02(\x03\x42\x34\n2org.whispersystems.signalservice.api.crypto.protos'
)


_ENVELOPEMETADATA = DESCRIPTOR.message_types_by_name["EnvelopeMetadata"]
_COMPLETEMESSAGE = DESCRIPTOR.message_types_by_name["CompleteMessage"]
EnvelopeMetadata = _reflection.GeneratedProtocolMessageType(
    "EnvelopeMetadata",
    (_message.Message,),
    {
        "DESCRIPTOR": _ENVELOPEMETADATA,
        "__module__": "MessageProcessing_pb2",
        # @@protoc_insertion_point(class_scope:signalservice.EnvelopeMetadata)
    },
)
_sym_db.RegisterMessage(EnvelopeMetadata)

CompleteMessage = _reflection.GeneratedProtocolMessageType(
    "CompleteMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _COMPLETEMESSAGE,
        "__module__": "MessageProcessing_pb2",
        # @@protoc_insertion_point(class_scope:signalservice.CompleteMessage)
    },
)
_sym_db.RegisterMessage(CompleteMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n2org.whispersystems.signalservice.api.crypto.protos"
    )
    _ENVELOPEMETADATA._serialized_start = 43
    _ENVELOPEMETADATA._serialized_end = 199
    _COMPLETEMESSAGE._serialized_start = 202
    _COMPLETEMESSAGE._serialized_end = 339
# @@protoc_insertion_point(module_scope)
