# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Payments.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePayments.proto\x12\x06signal\"\xb9\x04\n\x10MobileCoinLedger\x12\x19\n\x11\x64\x65precatedBalance\x18\x01 \x01(\x04\x12\x0f\n\x07\x62\x61lance\x18\x07 \x01(\x0c\x12%\n\x1d\x64\x65precatedTransferableBalance\x18\x02 \x01(\x04\x12\x1b\n\x13transferableBalance\x18\x08 \x01(\x0c\x12\x34\n\x0chighestBlock\x18\x03 \x01(\x0b\x32\x1e.signal.MobileCoinLedger.Block\x12\x15\n\rasOfTimeStamp\x18\x04 \x01(\x04\x12\x34\n\tspentTxos\x18\x05 \x03(\x0b\x32!.signal.MobileCoinLedger.OwnedTXO\x12\x36\n\x0bunspentTxos\x18\x06 \x03(\x0b\x32!.signal.MobileCoinLedger.OwnedTXO\x1a\xc8\x01\n\x08OwnedTXO\x12\x18\n\x10\x64\x65precatedAmount\x18\x01 \x01(\x04\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x0c\x12\x10\n\x08keyImage\x18\x02 \x01(\x0c\x12\x11\n\tpublicKey\x18\x03 \x01(\x0c\x12\x37\n\x0freceivedInBlock\x18\x04 \x01(\x0b\x32\x1e.signal.MobileCoinLedger.Block\x12\x34\n\x0cspentInBlock\x18\x05 \x01(\x0b\x32\x1e.signal.MobileCoinLedger.Block\x1a/\n\x05\x42lock\x12\x13\n\x0b\x62lockNumber\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\"\xb0\x01\n\x0fPaymentMetaData\x12X\n\x1bmobileCoinTxoIdentification\x18\x01 \x01(\x0b\x32\x33.signal.PaymentMetaData.MobileCoinTxoIdentification\x1a\x43\n\x1bMobileCoinTxoIdentification\x12\x11\n\tpublicKey\x18\x01 \x03(\x0c\x12\x11\n\tkeyImages\x18\x02 \x03(\x0c\x42-\n)org.thoughtcrime.securesms.payments.protoP\x01\x62\x06proto3')



_MOBILECOINLEDGER = DESCRIPTOR.message_types_by_name['MobileCoinLedger']
_MOBILECOINLEDGER_OWNEDTXO = _MOBILECOINLEDGER.nested_types_by_name['OwnedTXO']
_MOBILECOINLEDGER_BLOCK = _MOBILECOINLEDGER.nested_types_by_name['Block']
_PAYMENTMETADATA = DESCRIPTOR.message_types_by_name['PaymentMetaData']
_PAYMENTMETADATA_MOBILECOINTXOIDENTIFICATION = _PAYMENTMETADATA.nested_types_by_name['MobileCoinTxoIdentification']
MobileCoinLedger = _reflection.GeneratedProtocolMessageType('MobileCoinLedger', (_message.Message,), {

  'OwnedTXO' : _reflection.GeneratedProtocolMessageType('OwnedTXO', (_message.Message,), {
    'DESCRIPTOR' : _MOBILECOINLEDGER_OWNEDTXO,
    '__module__' : 'Payments_pb2'
    # @@protoc_insertion_point(class_scope:signal.MobileCoinLedger.OwnedTXO)
    })
  ,

  'Block' : _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {
    'DESCRIPTOR' : _MOBILECOINLEDGER_BLOCK,
    '__module__' : 'Payments_pb2'
    # @@protoc_insertion_point(class_scope:signal.MobileCoinLedger.Block)
    })
  ,
  'DESCRIPTOR' : _MOBILECOINLEDGER,
  '__module__' : 'Payments_pb2'
  # @@protoc_insertion_point(class_scope:signal.MobileCoinLedger)
  })
_sym_db.RegisterMessage(MobileCoinLedger)
_sym_db.RegisterMessage(MobileCoinLedger.OwnedTXO)
_sym_db.RegisterMessage(MobileCoinLedger.Block)

PaymentMetaData = _reflection.GeneratedProtocolMessageType('PaymentMetaData', (_message.Message,), {

  'MobileCoinTxoIdentification' : _reflection.GeneratedProtocolMessageType('MobileCoinTxoIdentification', (_message.Message,), {
    'DESCRIPTOR' : _PAYMENTMETADATA_MOBILECOINTXOIDENTIFICATION,
    '__module__' : 'Payments_pb2'
    # @@protoc_insertion_point(class_scope:signal.PaymentMetaData.MobileCoinTxoIdentification)
    })
  ,
  'DESCRIPTOR' : _PAYMENTMETADATA,
  '__module__' : 'Payments_pb2'
  # @@protoc_insertion_point(class_scope:signal.PaymentMetaData)
  })
_sym_db.RegisterMessage(PaymentMetaData)
_sym_db.RegisterMessage(PaymentMetaData.MobileCoinTxoIdentification)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n)org.thoughtcrime.securesms.payments.protoP\001'
  _MOBILECOINLEDGER._serialized_start=27
  _MOBILECOINLEDGER._serialized_end=596
  _MOBILECOINLEDGER_OWNEDTXO._serialized_start=347
  _MOBILECOINLEDGER_OWNEDTXO._serialized_end=547
  _MOBILECOINLEDGER_BLOCK._serialized_start=549
  _MOBILECOINLEDGER_BLOCK._serialized_end=596
  _PAYMENTMETADATA._serialized_start=599
  _PAYMENTMETADATA._serialized_end=775
  _PAYMENTMETADATA_MOBILECOINTXOIDENTIFICATION._serialized_start=708
  _PAYMENTMETADATA_MOBILECOINTXOIDENTIFICATION._serialized_end=775
# @@protoc_insertion_point(module_scope)
