# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Provisioning.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12Provisioning.proto\x12\rsignalservice" \n\x10ProvisioningUuid\x12\x0c\n\x04uuid\x18\x01 \x01(\t"4\n\x11ProvisionEnvelope\x12\x11\n\tpublicKey\x18\x01 \x01(\x0c\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c"\xbd\x02\n\x10ProvisionMessage\x12\x1c\n\x14\x61\x63iIdentityKeyPublic\x18\x01 \x01(\x0c\x12\x1d\n\x15\x61\x63iIdentityKeyPrivate\x18\x02 \x01(\x0c\x12\x1c\n\x14pniIdentityKeyPublic\x18\x0b \x01(\x0c\x12\x1d\n\x15pniIdentityKeyPrivate\x18\x0c \x01(\x0c\x12\x0b\n\x03\x61\x63i\x18\x08 \x01(\t\x12\x0b\n\x03pni\x18\n \x01(\t\x12\x0e\n\x06number\x18\x03 \x01(\t\x12\x18\n\x10provisioningCode\x18\x04 \x01(\t\x12\x11\n\tuserAgent\x18\x05 \x01(\t\x12\x12\n\nprofileKey\x18\x06 \x01(\x0c\x12\x14\n\x0creadReceipts\x18\x07 \x01(\x08\x12\x1b\n\x13provisioningVersion\x18\t \x01(\r\x12\x11\n\tmasterKey\x18\r \x01(\x0c*G\n\x13ProvisioningVersion\x12\x0b\n\x07INITIAL\x10\x00\x12\x12\n\x0eTABLET_SUPPORT\x10\x01\x12\x0b\n\x07\x43URRENT\x10\x01\x1a\x02\x10\x01\x42\x44\n.org.whispersystems.signalservice.internal.pushB\x12ProvisioningProtos'
)

_PROVISIONINGVERSION = DESCRIPTOR.enum_types_by_name["ProvisioningVersion"]
ProvisioningVersion = enum_type_wrapper.EnumTypeWrapper(_PROVISIONINGVERSION)
INITIAL = 0
TABLET_SUPPORT = 1
CURRENT = 1


_PROVISIONINGUUID = DESCRIPTOR.message_types_by_name["ProvisioningUuid"]
_PROVISIONENVELOPE = DESCRIPTOR.message_types_by_name["ProvisionEnvelope"]
_PROVISIONMESSAGE = DESCRIPTOR.message_types_by_name["ProvisionMessage"]
ProvisioningUuid = _reflection.GeneratedProtocolMessageType(
    "ProvisioningUuid",
    (_message.Message,),
    {
        "DESCRIPTOR": _PROVISIONINGUUID,
        "__module__": "Provisioning_pb2",
        # @@protoc_insertion_point(class_scope:signalservice.ProvisioningUuid)
    },
)
_sym_db.RegisterMessage(ProvisioningUuid)

ProvisionEnvelope = _reflection.GeneratedProtocolMessageType(
    "ProvisionEnvelope",
    (_message.Message,),
    {
        "DESCRIPTOR": _PROVISIONENVELOPE,
        "__module__": "Provisioning_pb2",
        # @@protoc_insertion_point(class_scope:signalservice.ProvisionEnvelope)
    },
)
_sym_db.RegisterMessage(ProvisionEnvelope)

ProvisionMessage = _reflection.GeneratedProtocolMessageType(
    "ProvisionMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _PROVISIONMESSAGE,
        "__module__": "Provisioning_pb2",
        # @@protoc_insertion_point(class_scope:signalservice.ProvisionMessage)
    },
)
_sym_db.RegisterMessage(ProvisionMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n.org.whispersystems.signalservice.internal.pushB\022ProvisioningProtos"
    )
    _PROVISIONINGVERSION._options = None
    _PROVISIONINGVERSION._serialized_options = b"\020\001"
    _PROVISIONINGVERSION._serialized_start = 445
    _PROVISIONINGVERSION._serialized_end = 516
    _PROVISIONINGUUID._serialized_start = 37
    _PROVISIONINGUUID._serialized_end = 69
    _PROVISIONENVELOPE._serialized_start = 71
    _PROVISIONENVELOPE._serialized_end = 123
    _PROVISIONMESSAGE._serialized_start = 126
    _PROVISIONMESSAGE._serialized_end = 443
# @@protoc_insertion_point(module_scope)
