# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResumableUploads.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ResumableUploads.proto\"\xc6\x01\n\x0fResumableUpload\x12\x11\n\tsecretKey\x18\x01 \x01(\x0c\x12\n\n\x02iv\x18\x02 \x01(\x0c\x12\x0e\n\x06\x63\x64nKey\x18\x03 \x01(\t\x12\x11\n\tcdnNumber\x18\x04 \x01(\r\x12\x10\n\x08location\x18\x05 \x01(\t\x12\x0f\n\x07timeout\x18\x06 \x01(\x04\x12(\n\x07headers\x18\x07 \x03(\x0b\x32\x17.ResumableUpload.Header\x1a$\n\x06Header\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tB$\n\"org.signal.protos.resumableuploadsb\x06proto3')



_RESUMABLEUPLOAD = DESCRIPTOR.message_types_by_name['ResumableUpload']
_RESUMABLEUPLOAD_HEADER = _RESUMABLEUPLOAD.nested_types_by_name['Header']
ResumableUpload = _reflection.GeneratedProtocolMessageType('ResumableUpload', (_message.Message,), {

  'Header' : _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
    'DESCRIPTOR' : _RESUMABLEUPLOAD_HEADER,
    '__module__' : 'ResumableUploads_pb2'
    # @@protoc_insertion_point(class_scope:ResumableUpload.Header)
    })
  ,
  'DESCRIPTOR' : _RESUMABLEUPLOAD,
  '__module__' : 'ResumableUploads_pb2'
  # @@protoc_insertion_point(class_scope:ResumableUpload)
  })
_sym_db.RegisterMessage(ResumableUpload)
_sym_db.RegisterMessage(ResumableUpload.Header)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"org.signal.protos.resumableuploads'
  _RESUMABLEUPLOAD._serialized_start=27
  _RESUMABLEUPLOAD._serialized_end=225
  _RESUMABLEUPLOAD_HEADER._serialized_start=189
  _RESUMABLEUPLOAD_HEADER._serialized_end=225
# @@protoc_insertion_point(module_scope)
