# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\rservice.proto\x12\rsignalservice"\xdd\x01\n\x07\x43ontent\x12\x14\n\x0c\x64\x61ta_message\x18\x01 \x01(\x0c\x12\x14\n\x0csync_message\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63\x61ll_message\x18\x03 \x01(\x0c\x12\x14\n\x0cnull_message\x18\x04 \x01(\x0c\x12\x17\n\x0freceipt_message\x18\x05 \x01(\x0c\x12\x16\n\x0etyping_message\x18\x06 \x01(\x0c\x12\'\n\x1fsender_key_distribution_message\x18\x07 \x01(\x0c\x12 \n\x18\x64\x65\x63ryption_error_message\x18\x08 \x01(\x0c"S\n\x16\x44\x65\x63ryptionErrorMessage\x12\x13\n\x0bratchet_key\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x11\n\tdevice_id\x18\x03 \x01(\r'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "service_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _globals["_CONTENT"]._serialized_start = 33
    _globals["_CONTENT"]._serialized_end = 254
    _globals["_DECRYPTIONERRORMESSAGE"]._serialized_start = 256
    _globals["_DECRYPTIONERRORMESSAGE"]._serialized_end = 339
# @@protoc_insertion_point(module_scope)
