# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StickerResources.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16StickerResources.proto\x12\rsignalservice\"\xbb\x01\n\x04Pack\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12*\n\x05\x63over\x18\x03 \x01(\x0b\x32\x1b.signalservice.Pack.Sticker\x12-\n\x08stickers\x18\x04 \x03(\x0b\x32\x1b.signalservice.Pack.Sticker\x1a\x39\n\x07Sticker\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x65moji\x18\x02 \x01(\t\x12\x13\n\x0b\x63ontentType\x18\x03 \x01(\tBB\n1org.whispersystems.signalservice.internal.stickerB\rStickerProtos')



_PACK = DESCRIPTOR.message_types_by_name['Pack']
_PACK_STICKER = _PACK.nested_types_by_name['Sticker']
Pack = _reflection.GeneratedProtocolMessageType('Pack', (_message.Message,), {

  'Sticker' : _reflection.GeneratedProtocolMessageType('Sticker', (_message.Message,), {
    'DESCRIPTOR' : _PACK_STICKER,
    '__module__' : 'StickerResources_pb2'
    # @@protoc_insertion_point(class_scope:signalservice.Pack.Sticker)
    })
  ,
  'DESCRIPTOR' : _PACK,
  '__module__' : 'StickerResources_pb2'
  # @@protoc_insertion_point(class_scope:signalservice.Pack)
  })
_sym_db.RegisterMessage(Pack)
_sym_db.RegisterMessage(Pack.Sticker)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n1org.whispersystems.signalservice.internal.stickerB\rStickerProtos'
  _PACK._serialized_start=42
  _PACK._serialized_end=229
  _PACK_STICKER._serialized_start=172
  _PACK_STICKER._serialized_end=229
# @@protoc_insertion_point(module_scope)
