# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svr2.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsvr2.proto\x12\x0forg.signal.svr2\"\xb0\x01\n\x07Request\x12\x30\n\x06\x62\x61\x63kup\x18\x02 \x01(\x0b\x32\x1e.org.signal.svr2.BackupRequestH\x00\x12\x32\n\x07restore\x18\x03 \x01(\x0b\x32\x1f.org.signal.svr2.RestoreRequestH\x00\x12\x30\n\x06\x64\x65lete\x18\x04 \x01(\x0b\x32\x1e.org.signal.svr2.DeleteRequestH\x00\x42\x07\n\x05innerJ\x04\x08\x01\x10\x02\"\xae\x01\n\x08Response\x12\x31\n\x06\x62\x61\x63kup\x18\x01 \x01(\x0b\x32\x1f.org.signal.svr2.BackupResponseH\x00\x12\x33\n\x07restore\x18\x02 \x01(\x0b\x32 .org.signal.svr2.RestoreResponseH\x00\x12\x31\n\x06\x64\x65lete\x18\x03 \x01(\x0b\x32\x1f.org.signal.svr2.DeleteResponseH\x00\x42\x07\n\x05inner\"=\n\rBackupRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0b\n\x03pin\x18\x02 \x01(\x0c\x12\x11\n\tmax_tries\x18\x03 \x01(\r\"z\n\x0e\x42\x61\x63kupResponse\x12\x36\n\x06status\x18\x01 \x01(\x0e\x32&.org.signal.svr2.BackupResponse.Status\"0\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x13\n\x0fREQUEST_INVALID\x10\x02\"\x1d\n\x0eRestoreRequest\x12\x0b\n\x03pin\x18\x01 \x01(\x0c\"\xb8\x01\n\x0fRestoreResponse\x12\x37\n\x06status\x18\x01 \x01(\x0e\x32\'.org.signal.svr2.RestoreResponse.Status\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05tries\x18\x03 \x01(\r\"O\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0b\n\x07MISSING\x10\x02\x12\x10\n\x0cPIN_MISMATCH\x10\x03\x12\x13\n\x0fREQUEST_INVALID\x10\x04\"\x0f\n\rDeleteRequest\"\x10\n\x0e\x44\x65leteResponseb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
_BACKUPREQUEST = DESCRIPTOR.message_types_by_name['BackupRequest']
_BACKUPRESPONSE = DESCRIPTOR.message_types_by_name['BackupResponse']
_RESTOREREQUEST = DESCRIPTOR.message_types_by_name['RestoreRequest']
_RESTORERESPONSE = DESCRIPTOR.message_types_by_name['RestoreResponse']
_DELETEREQUEST = DESCRIPTOR.message_types_by_name['DeleteRequest']
_DELETERESPONSE = DESCRIPTOR.message_types_by_name['DeleteResponse']
_BACKUPRESPONSE_STATUS = _BACKUPRESPONSE.enum_types_by_name['Status']
_RESTORERESPONSE_STATUS = _RESTORERESPONSE.enum_types_by_name['Status']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'svr2_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.svr2.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'svr2_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.svr2.Response)
  })
_sym_db.RegisterMessage(Response)

BackupRequest = _reflection.GeneratedProtocolMessageType('BackupRequest', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPREQUEST,
  '__module__' : 'svr2_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.svr2.BackupRequest)
  })
_sym_db.RegisterMessage(BackupRequest)

BackupResponse = _reflection.GeneratedProtocolMessageType('BackupResponse', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPRESPONSE,
  '__module__' : 'svr2_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.svr2.BackupResponse)
  })
_sym_db.RegisterMessage(BackupResponse)

RestoreRequest = _reflection.GeneratedProtocolMessageType('RestoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESTOREREQUEST,
  '__module__' : 'svr2_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.svr2.RestoreRequest)
  })
_sym_db.RegisterMessage(RestoreRequest)

RestoreResponse = _reflection.GeneratedProtocolMessageType('RestoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESTORERESPONSE,
  '__module__' : 'svr2_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.svr2.RestoreResponse)
  })
_sym_db.RegisterMessage(RestoreResponse)

DeleteRequest = _reflection.GeneratedProtocolMessageType('DeleteRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEREQUEST,
  '__module__' : 'svr2_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.svr2.DeleteRequest)
  })
_sym_db.RegisterMessage(DeleteRequest)

DeleteResponse = _reflection.GeneratedProtocolMessageType('DeleteResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETERESPONSE,
  '__module__' : 'svr2_pb2'
  # @@protoc_insertion_point(class_scope:org.signal.svr2.DeleteResponse)
  })
_sym_db.RegisterMessage(DeleteResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=32
  _REQUEST._serialized_end=208
  _RESPONSE._serialized_start=211
  _RESPONSE._serialized_end=385
  _BACKUPREQUEST._serialized_start=387
  _BACKUPREQUEST._serialized_end=448
  _BACKUPRESPONSE._serialized_start=450
  _BACKUPRESPONSE._serialized_end=572
  _BACKUPRESPONSE_STATUS._serialized_start=524
  _BACKUPRESPONSE_STATUS._serialized_end=572
  _RESTOREREQUEST._serialized_start=574
  _RESTOREREQUEST._serialized_end=603
  _RESTORERESPONSE._serialized_start=606
  _RESTORERESPONSE._serialized_end=790
  _RESTORERESPONSE_STATUS._serialized_start=711
  _RESTORERESPONSE_STATUS._serialized_end=790
  _DELETEREQUEST._serialized_start=792
  _DELETEREQUEST._serialized_end=807
  _DELETERESPONSE._serialized_start=809
  _DELETERESPONSE._serialized_end=825
# @@protoc_insertion_point(module_scope)
