# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: svr3.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nsvr3.proto\x12\x0bsvr3.client"\xcc\x01\n\x07Request\x12,\n\x06\x63reate\x18\x01 \x01(\x0b\x32\x1a.svr3.client.CreateRequestH\x00\x12\x30\n\x08\x65valuate\x18\x02 \x01(\x0b\x32\x1c.svr3.client.EvaluateRequestH\x00\x12,\n\x06remove\x18\x03 \x01(\x0b\x32\x1a.svr3.client.RemoveRequestH\x00\x12*\n\x05query\x18\x04 \x01(\x0b\x32\x19.svr3.client.QueryRequestH\x00\x42\x07\n\x05inner"\xd1\x01\n\x08Response\x12-\n\x06\x63reate\x18\x01 \x01(\x0b\x32\x1b.svr3.client.CreateResponseH\x00\x12\x31\n\x08\x65valuate\x18\x02 \x01(\x0b\x32\x1d.svr3.client.EvaluateResponseH\x00\x12-\n\x06remove\x18\x03 \x01(\x0b\x32\x1b.svr3.client.RemoveResponseH\x00\x12+\n\x05query\x18\x04 \x01(\x0b\x32\x1a.svr3.client.QueryResponseH\x00\x42\x07\n\x05inner";\n\rCreateRequest\x12\x11\n\tmax_tries\x18\x01 \x01(\r\x12\x17\n\x0f\x62linded_element\x18\x02 \x01(\x0c"\x9c\x01\n\x0e\x43reateResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32".svr3.client.CreateResponse.Status\x12\x19\n\x11\x65valuated_element\x18\x02 \x01(\x0c";\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x13\n\x0fINVALID_REQUEST\x10\x02\x12\t\n\x05\x45RROR\x10\x03"*\n\x0f\x45valuateRequest\x12\x17\n\x0f\x62linded_element\x18\x01 \x01(\x0c"\xc6\x01\n\x10\x45valuateResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.svr3.client.EvaluateResponse.Status\x12\x19\n\x11\x65valuated_element\x18\x02 \x01(\x0c\x12\x17\n\x0ftries_remaining\x18\x03 \x01(\r"H\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0b\n\x07MISSING\x10\x02\x12\x13\n\x0fINVALID_REQUEST\x10\x03\x12\t\n\x05\x45RROR\x10\x04"\x0f\n\rRemoveRequest"\x10\n\x0eRemoveResponse"\x0e\n\x0cQueryRequest"\x85\x01\n\rQueryResponse\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.svr3.client.QueryResponse.Status\x12\x17\n\x0ftries_remaining\x18\x02 \x01(\r"(\n\x06Status\x12\t\n\x05UNSET\x10\x00\x12\x06\n\x02OK\x10\x01\x12\x0b\n\x07MISSING\x10\x02\x42\x02H\x03\x62\x06proto3'
)


_REQUEST = DESCRIPTOR.message_types_by_name["Request"]
_RESPONSE = DESCRIPTOR.message_types_by_name["Response"]
_CREATEREQUEST = DESCRIPTOR.message_types_by_name["CreateRequest"]
_CREATERESPONSE = DESCRIPTOR.message_types_by_name["CreateResponse"]
_EVALUATEREQUEST = DESCRIPTOR.message_types_by_name["EvaluateRequest"]
_EVALUATERESPONSE = DESCRIPTOR.message_types_by_name["EvaluateResponse"]
_REMOVEREQUEST = DESCRIPTOR.message_types_by_name["RemoveRequest"]
_REMOVERESPONSE = DESCRIPTOR.message_types_by_name["RemoveResponse"]
_QUERYREQUEST = DESCRIPTOR.message_types_by_name["QueryRequest"]
_QUERYRESPONSE = DESCRIPTOR.message_types_by_name["QueryResponse"]
_CREATERESPONSE_STATUS = _CREATERESPONSE.enum_types_by_name["Status"]
_EVALUATERESPONSE_STATUS = _EVALUATERESPONSE.enum_types_by_name["Status"]
_QUERYRESPONSE_STATUS = _QUERYRESPONSE.enum_types_by_name["Status"]
Request = _reflection.GeneratedProtocolMessageType(
    "Request",
    (_message.Message,),
    {
        "DESCRIPTOR": _REQUEST,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.Request)
    },
)
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType(
    "Response",
    (_message.Message,),
    {
        "DESCRIPTOR": _RESPONSE,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.Response)
    },
)
_sym_db.RegisterMessage(Response)

CreateRequest = _reflection.GeneratedProtocolMessageType(
    "CreateRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _CREATEREQUEST,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.CreateRequest)
    },
)
_sym_db.RegisterMessage(CreateRequest)

CreateResponse = _reflection.GeneratedProtocolMessageType(
    "CreateResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _CREATERESPONSE,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.CreateResponse)
    },
)
_sym_db.RegisterMessage(CreateResponse)

EvaluateRequest = _reflection.GeneratedProtocolMessageType(
    "EvaluateRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _EVALUATEREQUEST,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.EvaluateRequest)
    },
)
_sym_db.RegisterMessage(EvaluateRequest)

EvaluateResponse = _reflection.GeneratedProtocolMessageType(
    "EvaluateResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _EVALUATERESPONSE,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.EvaluateResponse)
    },
)
_sym_db.RegisterMessage(EvaluateResponse)

RemoveRequest = _reflection.GeneratedProtocolMessageType(
    "RemoveRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _REMOVEREQUEST,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.RemoveRequest)
    },
)
_sym_db.RegisterMessage(RemoveRequest)

RemoveResponse = _reflection.GeneratedProtocolMessageType(
    "RemoveResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _REMOVERESPONSE,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.RemoveResponse)
    },
)
_sym_db.RegisterMessage(RemoveResponse)

QueryRequest = _reflection.GeneratedProtocolMessageType(
    "QueryRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _QUERYREQUEST,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.QueryRequest)
    },
)
_sym_db.RegisterMessage(QueryRequest)

QueryResponse = _reflection.GeneratedProtocolMessageType(
    "QueryResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _QUERYRESPONSE,
        "__module__": "svr3_pb2",
        # @@protoc_insertion_point(class_scope:svr3.client.QueryResponse)
    },
)
_sym_db.RegisterMessage(QueryResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"H\003"
    _REQUEST._serialized_start = 28
    _REQUEST._serialized_end = 232
    _RESPONSE._serialized_start = 235
    _RESPONSE._serialized_end = 444
    _CREATEREQUEST._serialized_start = 446
    _CREATEREQUEST._serialized_end = 505
    _CREATERESPONSE._serialized_start = 508
    _CREATERESPONSE._serialized_end = 664
    _CREATERESPONSE_STATUS._serialized_start = 605
    _CREATERESPONSE_STATUS._serialized_end = 664
    _EVALUATEREQUEST._serialized_start = 666
    _EVALUATEREQUEST._serialized_end = 708
    _EVALUATERESPONSE._serialized_start = 711
    _EVALUATERESPONSE._serialized_end = 909
    _EVALUATERESPONSE_STATUS._serialized_start = 837
    _EVALUATERESPONSE_STATUS._serialized_end = 909
    _REMOVEREQUEST._serialized_start = 911
    _REMOVEREQUEST._serialized_end = 926
    _REMOVERESPONSE._serialized_start = 928
    _REMOVERESPONSE._serialized_end = 944
    _QUERYREQUEST._serialized_start = 946
    _QUERYREQUEST._serialized_end = 960
    _QUERYRESPONSE._serialized_start = 963
    _QUERYRESPONSE._serialized_end = 1096
    _QUERYRESPONSE_STATUS._serialized_start = 837
    _QUERYRESPONSE_STATUS._serialized_end = 877
# @@protoc_insertion_point(module_scope)
