# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WebSocketResources.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18WebSocketResources.proto\x12\rsignalservice\"`\n\x17WebSocketRequestMessage\x12\x0c\n\x04verb\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\x12\x0f\n\x07headers\x18\x05 \x03(\t\x12\n\n\x02id\x18\x04 \x01(\x04\"f\n\x18WebSocketResponseMessage\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07headers\x18\x05 \x03(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\x0c\"\xea\x01\n\x10WebSocketMessage\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.signalservice.WebSocketMessage.Type\x12\x37\n\x07request\x18\x02 \x01(\x0b\x32&.signalservice.WebSocketRequestMessage\x12\x39\n\x08response\x18\x03 \x01(\x0b\x32\'.signalservice.WebSocketResponseMessage\".\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07REQUEST\x10\x01\x12\x0c\n\x08RESPONSE\x10\x02\x42\x46\n3org.whispersystems.signalservice.internal.websocketB\x0fWebSocketProtos')



_WEBSOCKETREQUESTMESSAGE = DESCRIPTOR.message_types_by_name['WebSocketRequestMessage']
_WEBSOCKETRESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['WebSocketResponseMessage']
_WEBSOCKETMESSAGE = DESCRIPTOR.message_types_by_name['WebSocketMessage']
_WEBSOCKETMESSAGE_TYPE = _WEBSOCKETMESSAGE.enum_types_by_name['Type']
WebSocketRequestMessage = _reflection.GeneratedProtocolMessageType('WebSocketRequestMessage', (_message.Message,), {
  'DESCRIPTOR' : _WEBSOCKETREQUESTMESSAGE,
  '__module__' : 'WebSocketResources_pb2'
  # @@protoc_insertion_point(class_scope:signalservice.WebSocketRequestMessage)
  })
_sym_db.RegisterMessage(WebSocketRequestMessage)

WebSocketResponseMessage = _reflection.GeneratedProtocolMessageType('WebSocketResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _WEBSOCKETRESPONSEMESSAGE,
  '__module__' : 'WebSocketResources_pb2'
  # @@protoc_insertion_point(class_scope:signalservice.WebSocketResponseMessage)
  })
_sym_db.RegisterMessage(WebSocketResponseMessage)

WebSocketMessage = _reflection.GeneratedProtocolMessageType('WebSocketMessage', (_message.Message,), {
  'DESCRIPTOR' : _WEBSOCKETMESSAGE,
  '__module__' : 'WebSocketResources_pb2'
  # @@protoc_insertion_point(class_scope:signalservice.WebSocketMessage)
  })
_sym_db.RegisterMessage(WebSocketMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n3org.whispersystems.signalservice.internal.websocketB\017WebSocketProtos'
  _WEBSOCKETREQUESTMESSAGE._serialized_start=43
  _WEBSOCKETREQUESTMESSAGE._serialized_end=139
  _WEBSOCKETRESPONSEMESSAGE._serialized_start=141
  _WEBSOCKETRESPONSEMESSAGE._serialized_end=243
  _WEBSOCKETMESSAGE._serialized_start=246
  _WEBSOCKETMESSAGE._serialized_end=480
  _WEBSOCKETMESSAGE_TYPE._serialized_start=434
  _WEBSOCKETMESSAGE_TYPE._serialized_end=480
# @@protoc_insertion_point(module_scope)
