# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wire.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nwire.proto\x12\x11signal.proto.wire"c\n\rSignalMessage\x12\x13\n\x0bratchet_key\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63ounter\x18\x02 \x01(\r\x12\x18\n\x10previous_counter\x18\x03 \x01(\r\x12\x12\n\nciphertext\x18\x04 \x01(\x0c"\xca\x01\n\x13PreKeySignalMessage\x12\x17\n\x0fregistration_id\x18\x05 \x01(\r\x12\x12\n\npre_key_id\x18\x01 \x01(\r\x12\x19\n\x11signed_pre_key_id\x18\x06 \x01(\r\x12\x18\n\x10kyber_pre_key_id\x18\x07 \x01(\r\x12\x18\n\x10kyber_ciphertext\x18\x08 \x01(\x0c\x12\x10\n\x08\x62\x61se_key\x18\x02 \x01(\x0c\x12\x14\n\x0cidentity_key\x18\x03 \x01(\x0c\x12\x0f\n\x07message\x18\x04 \x01(\x0c"f\n\x10SenderKeyMessage\x12\x19\n\x11\x64istribution_uuid\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hain_id\x18\x02 \x01(\r\x12\x11\n\titeration\x18\x03 \x01(\r\x12\x12\n\nciphertext\x18\x04 \x01(\x0c"\x86\x01\n\x1cSenderKeyDistributionMessage\x12\x19\n\x11\x64istribution_uuid\x18\x01 \x01(\x0c\x12\x10\n\x08\x63hain_id\x18\x02 \x01(\r\x12\x11\n\titeration\x18\x03 \x01(\r\x12\x11\n\tchain_key\x18\x04 \x01(\x0c\x12\x13\n\x0bsigning_key\x18\x05 \x01(\x0c'
)


_SIGNALMESSAGE = DESCRIPTOR.message_types_by_name["SignalMessage"]
_PREKEYSIGNALMESSAGE = DESCRIPTOR.message_types_by_name["PreKeySignalMessage"]
_SENDERKEYMESSAGE = DESCRIPTOR.message_types_by_name["SenderKeyMessage"]
_SENDERKEYDISTRIBUTIONMESSAGE = DESCRIPTOR.message_types_by_name[
    "SenderKeyDistributionMessage"
]
SignalMessage = _reflection.GeneratedProtocolMessageType(
    "SignalMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _SIGNALMESSAGE,
        "__module__": "wire_pb2",
        # @@protoc_insertion_point(class_scope:signal.proto.wire.SignalMessage)
    },
)
_sym_db.RegisterMessage(SignalMessage)

PreKeySignalMessage = _reflection.GeneratedProtocolMessageType(
    "PreKeySignalMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _PREKEYSIGNALMESSAGE,
        "__module__": "wire_pb2",
        # @@protoc_insertion_point(class_scope:signal.proto.wire.PreKeySignalMessage)
    },
)
_sym_db.RegisterMessage(PreKeySignalMessage)

SenderKeyMessage = _reflection.GeneratedProtocolMessageType(
    "SenderKeyMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _SENDERKEYMESSAGE,
        "__module__": "wire_pb2",
        # @@protoc_insertion_point(class_scope:signal.proto.wire.SenderKeyMessage)
    },
)
_sym_db.RegisterMessage(SenderKeyMessage)

SenderKeyDistributionMessage = _reflection.GeneratedProtocolMessageType(
    "SenderKeyDistributionMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _SENDERKEYDISTRIBUTIONMESSAGE,
        "__module__": "wire_pb2",
        # @@protoc_insertion_point(class_scope:signal.proto.wire.SenderKeyDistributionMessage)
    },
)
_sym_db.RegisterMessage(SenderKeyDistributionMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _SIGNALMESSAGE._serialized_start = 33
    _SIGNALMESSAGE._serialized_end = 132
    _PREKEYSIGNALMESSAGE._serialized_start = 135
    _PREKEYSIGNALMESSAGE._serialized_end = 337
    _SENDERKEYMESSAGE._serialized_start = 339
    _SENDERKEYMESSAGE._serialized_end = 441
    _SENDERKEYDISTRIBUTIONMESSAGE._serialized_start = 444
    _SENDERKEYDISTRIBUTIONMESSAGE._serialized_end = 578
# @@protoc_insertion_point(module_scope)
