[package]
name = "signal-protocol"
version = "0.2.1"
authors = ["jen <jen@freedom.press>"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
rand = "0.7.3"
libsignal-protocol-rust = { git = "https://github.com/freedomofpress/libsignal-client", rev="9a7785686bc049d9282d6410b1412c66df80040c" }
pyo3 = { version = "0.12.4", features = ["extension-module"] }

[lib]
name = "signal_protocol"
crate-type = ["cdylib"]
