[package]
name = "signal-protocol"
version = "0.2.1"
authors = ["jen <jen@freedom.press>"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
rand = "0.7.3"
libsignal-protocol-rust = { git = "https://github.com/freedomofpress/libsignal-client", branch="build" }
pyo3 = { version = "0.12.1", features = ["extension-module"] }

[lib]
name = "signal_protocol"
crate-type = ["cdylib"]
