[package]
name = "signal-protocol"
version = "0.2.3-alpha1"
authors = [""]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
rand = "0.8"
mac_address = "1.1.7"

libsignal-protocol = { git = "https://github.com/signalapp/libsignal", tag="v0.61.0" }
libsignal-core = { git = "https://github.com/signalapp/libsignal", version = "0.1.0" }
libsignal-keytrans = { git = "https://github.com/signalapp/libsignal", version = "0.0.1" }
signal-crypto = { git = "https://github.com/signalapp/libsignal", version = "0.1.0" }
libsignal-account-keys = { git = "https://github.com/signalapp/libsignal", version = "0.1.0", features = ["serde"]}
device-transfer = { git = "https://github.com/signalapp/libsignal", version = "0.1.0"}
libsignal-net = { git = "https://github.com/signalapp/libsignal", version = "0.1.0" }
#zkgroup = { git = "https://github.com/signalapp/libsignal", version = "0.9.0" }

pyo3 = { version = "0.22.5", features = ["extension-module", "multiple-pymethods"] }
pyo3-log = "0.11.0"
futures = "0.3.7"
rand_core = { version = "0.6.4", default-features = false }
uuid = { version = "1.11.0", features = ["v1", "v3", "v4", "v5", "v6", "v7", "v8", "fast-rng"]}
serde = {version = "1.0", features = ["derive"]}
serde_json = {version = "1.0"}
base64 = "0.22.1"

[patch.crates-io]
boring = { git = "https://github.com/signalapp/boring", tag = "signal-v4.9.0b" }
boring-sys = { git = "https://github.com/signalapp/boring", tag = "signal-v4.9.0b" }

[lib]
name = "signal_protocol"
crate-type = ["cdylib"]
