[package]
name = "signal-protocol"
version = "0.1.0"
authors = ["jen <jen@freedom.press>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
libsignal-protocol-rust = { git = "https://github.com/redshiftzero/libsignal-protocol-rust" }
pyo3 = { version = "0.12.1", features = ["extension-module"] }

[lib]
name = "signal_protocol"
crate-type = ["cdylib"]
