[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "signal-protocol"
version = "0.2.3-alpha1"
description = "Rust extension providing Python bindings to the signal protocol"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "AGPL-3.0-or-later"}
classifiers = [
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Rust",
]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "signal_protocol"
include = ["signal_protocol/py.typed", "signal_protocol/*.pyi"]
manifest-path = "Cargo.toml"
