version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install rust
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run:
          name: Install dependencies and run tests
          command: |
            source $HOME/.cargo/env
            virtualenv --python python3 .venv
            source .venv/bin/activate
            pip install -r requirements.txt
            python setup.py develop
            pytest -v tests/

  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install rust
          command: |
            curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run:
          name: Build wheels.
          command: |
            source $HOME/.cargo/env
            virtualenv --python python3 .venv
            source .venv/bin/activate
            pip install -r requirements.txt
            python setup.py install
            cd ..
            python3 -c "import signal_protocol"  # Check imports work

workflows:
  version: 2
  jobs_per_pr:
    jobs:
      - test
      - build
