class DeviceId:
    def __init__(device_id: int) -> None: ...

class ProtocolAddress:
    def __init__(name: str, device_id: int) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def device_id(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
