class KeyPair:
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...

    def generate(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def public_key(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def private_key(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def serialize(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def calculate_signature(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def calculate_agreement(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def from_public_and_private(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...


class PrivateKey:
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...

    def deserialize(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def serialize(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def calculate_signature(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def calculate_agreement(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def public_key(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...


class PublicKey:
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...

    def deserialize(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def serialize(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def verify_signature(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...


def generate_keypair():
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...


def verify_signature():
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...
