class SignalProtocolException:
    """
    <<<<<<<
    [AUTOGENERATED] -- TODO: adapt (if needed) and remove me
    =======
    Common base class for all non-exit exceptions.
    >>>>>>>
    """

    ...
