def create_keys_data():
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...

def create_registration():
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...

def create_registration_keys():
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...
