class DeploymentMode:
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""

    ...

    def byte(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def get_associated_key(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

class KeyTransparency:
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""

    ...

    def verify_search(self):
        """
        <<<<<<<
        [AUTOGENERATED] -- TODO: adapt (if needed) and remove me
        =======
        Checks that the output of a Search operation is valid and updates the client's stored data. res. value. value may only be consumed by the application if this function returns successfully.
        >>>>>>>
        """
        ...

    def verify_distinguished(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def truncate_search_response(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def verify_monitor(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def verify_update(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

class PublicConfig:
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""

    ...

class SlimSearchRequest:
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""

    ...

class VerifyingKey:
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""

    ...

    def from_bytes(self):
        """
        <<<<<<<
        [AUTOGENERATED] -- TODO: adapt (if needed) and remove me
        =======
        The caller **is responsible** for ensuring that the bytes passed into this method actually represent

        a curve25519_dalek::curve::CompressedEdwardsY and that said compressed point is actually a point on the curve.
        >>>>>>>
        """
        ...

    def is_weak(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def verify_strict(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

class VrfPublicKey:
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""

    ...

    def as_bytes(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...

    def proof_to_hash(self):
        """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
        ...
