class Auth:
    def __init__(self, username: str, password: str): ...
    def from_uid_and_secret(self): ...
    def otp(self): ...
    def username(self): ...
    def password(self): ...
    def as_http_header(self) -> tuple[str, str]:
        """
        Returns:
            A HTTP header tuple (name, value) containing the Authorization header name
            and its Basic auth value for server authentication.
        """
