class Auth:
    def __init__(self, username: str, password: str): ...
    def from_uid_and_secret(self): ...
    def otp(self): ...
    def username(self): ...
    def password(self): ...
    def as_http_header(self) -> (str, str):
        """
        :return: Return a HTTP header tuple (name, value) for this auth instance that can be used to authenticate with a server.
        """
