def message_decrypt():
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...


def message_decrypt_prekey():
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...


def message_decrypt_signal():
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...


def message_encrypt():
    """[AUTOGENERATED] -- TODO: adapt (if needed) and remove me"""
    ...
